version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: meduza3/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./front/codenotarydeps
      dockerfile: Dockerfile.frontend
    image: meduza3/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
    restart: unless-stopped

networks:
  default:
    driver: bridge
