version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: go-server
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.front
    container_name: remix-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
    - API_URL=http://backend:8080


networks:
  app-network:
    driver: bridge
