# Stage 1: Build
FROM golang:1.23 AS builder
WORKDIR /server
COPY . .
RUN GOOS=linux go build -a -installsuffix cgo -o server .
RUN ls -lh /server

# Stage 2: Run  
FROM golang:1.23-bullseye
WORKDIR /server
COPY . .
RUN go build -o server .
EXPOSE 8080
ENTRYPOINT ["./server"]